### ISSUE TITLE
[🐛] 404 response from Snyk API (solution)

### ISSUE THREAD

**Issue by JacobValdemar** [snyk-tech-services/backstage-plugin-snyk#11]
### Expected behaviour
Plugin works.

### Actual behaviour
Plugin is recieving 404 responses from snyk

### Steps to reproduce
Follow guide

### Solution
My solution to this problem was to change the proxy to something like:

```
'/snyk':
    target: https://snyk.io/api/v1
    headers:
      User-Agent: tech-services/backstage-plugin/1.0
      Authorization:
        $env: SNYK_TOKEN
    pathRewrite:
      '^/proxy/snyk/': '/'
```

Maybe add this to the installation guide, that if you get 404 from the API you can try with some path rewrite :)
