### ISSUE TITLE
[🐛] 404 - Failed fetching Projects list snyk data

### ISSUE THREAD

**Issue by schultzp2020** [snyk-tech-services/backstage-plugin-snyk#124]
- `node -v`: 18.12.1
- `yarn -v`: 3.4.1
- OS: (e.g. OSX, Linux, Windows, ...) Windows
- Command run: (e.g. `snyk-api-import ...`, ...) 1.2.7

### Expected behaviour
Please share _expected_ behaviour.

`<EntitySnykContent />` should render successfully without a 404 error.

### Actual behaviour
Please share _problematic_ behaviour you are seeing.

`<EntitySnykContent />` renders with a 404 error.

### Steps to reproduce
Please share _minimal_ steps needed to reproduce your issue. Ideally
a paired down manifest / project to showcase the problem that can also
be used for testing.

I followed the README guide.

Steps I took to try to debug:

- Followed the recommended proxy 404 error workaround
- Changed the token to be incorrect which gave me a 401 auth error

### Debug log
If applicable, please add `DEBUG=*snyk* <command here>` before your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

N/A

**Comment by aarlaud** [comment]
Hello there, I'm not able to reproduce this issue but noticed something wrong in the readme instruction.
Can you verify you're running this correctly following this doc update? https://github.com/snyk-tech-services/backstage-plugin-snyk/pull/125/files

**Comment by schultzp2020** [comment]
Hey @aarlaud, it still does not work for us. Here is the branch/pr you can use to reproduce the issue. https://github.com/janus-idp/backstage-showcase/pull/112

**Comment by aarlaud** [comment]
Making notes for action.
Shows Project Not found despite project being found but not being loaded due to API access. Making note here to improve error handling in SnykEntityComponent to handle error better, most likely when generateSnykTabForProject ends up in error.

**Comment by jcospina** [comment]
Is this a known issue? i have the following config for the proxy:
```
  '/snyk':
    target: 'https://api.snyk.io'
    headers:
      User-Agent: tech-services/backstage-plugin/1.0
      Authorization: 'token REDACTED'
    pathRewrite:
      '^/proxy/snyk/': '/'
```
And i'm getting Error 404 - Failed fetching Targets list snyk data. When testing on postman hitting the snyk api directly it works (which means the token is valid) but the backstage proxy doesn't

**Comment by swnia** [comment]
Apparently, in the meantime the proxy settings have to be updated to this:
```yaml
    '/snyk':
      target: https://api.snyk.io/
      headers:
        User-Agent: tech-services/backstage-plugin/1.0
        Authorization:
          $env: SNYK_TOKEN
      pathRewrite:
        '^/api/proxy/snyk/': '/'
```

**Comment by aarlaud** [comment]
Hum... my setup works with this alone
```
proxy:
  endpoints:
    /snyk:
      target: https://api.snyk.io/
      headers:
        User-Agent: tech-services/backstage-plugin/1.0
        Authorization: token ${SNYK_TOKEN}
```

Looks like you need a rewrite path for some reason. I'd like to add this to the README, but I'm unclear why you need it and I don't, and why it doesn't seem to be for everyone.
Is there a proxy setting somewhere in your setup that differs from the basic create-app scenario?
