### ISSUE TITLE
[🐛] Error "Warning: Unable to find snyk project details"

### ISSUE THREAD

**Issue by ducquang92** [snyk-tech-services/backstage-plugin-snyk#151]
Hi,
I recently tried to use the plugin. I followed the guideline in https://github.com/snyk-tech-services/backstage-plugin-snyk, but nothing shows up in the entity page. While trying to debug, I tried to remove the <EntitySwitch.Case if={isSnykAvailable}> and the Snyk section shows up but with the error "Warning: Unable to find snyk project details" (so it seems like the isSnykAvailable variable is false) . I tried different annotations (snyk.io/org-name together with snyk.io/projects-ids, snyk.io/target-id) but none worked. The integrated SCM is Bitbucket Server.

I opened a ticket request to Snyk support (ticket ID 54813) and had the troubleshooting session but we did not find out the cause of the issue. I was asked to open this ticket here.

The content of the entities.yaml looks like this:

```
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
  annotations:
    snyk.io/org-name: OrgTemplate
    snyk.io/target-id: c8b7c792-2c6d-4b1d-8b80-8b125fc9b25d
spec:
  type: website
  lifecycle: experimental
  owner: quang-test
  system: examples
  providesApis: [example-grpc-api]
```

The error looks like below:
<img width="1440" alt="Screenshot 2023-07-11 at 15 36 46" src="https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/15622356/59e30eb0-7d3d-4ffc-9481-80487cb24114">

The SNYK_TOKEN variable is set and I verified that token is valid.
Do you know what could I have configured wrong?

Thanks,
Quang
