### ISSUE TITLE
[🙏]

### ISSUE THREAD

**Issue by johnsungunity** [snyk-tech-services/backstage-plugin-snyk#184]
I couldn't find a note on how to implement multiple Snyk orgs using the new feature
https://github.com/snyk-tech-services/backstage-plugin-snyk/pull/167

My use case is : 
- Snyk Org A  has one API key 
- Snyk Org B has it's own API key 

In Backstage I can only see in the [docs](https://github.com/snyk-tech-services/backstage-plugin-snyk) to pass one API key (AFIAK)
```

proxy:
  endpoints:
    ...
    /snyk:
      # Host of the API to use on the calls.
      # If you use EU or AU Snyk account, change this to https://api.eu.snyk.io/ or https://api.au.snyk.io/
      target: https://api.snyk.io/
      headers:
        User-Agent: tech-services/backstage-plugin/1.0
        Authorization: token ${SNYK_TOKEN}
    ...
```

**Describe expected behaviour**
A note in the docs on how to handle this scenario with  multiple API keys.
Or is there a more simple way to do this?
