### ISSUE TITLE
[🐛] Error: No Snyk org/project-ids listed

### ISSUE THREAD

**Issue by olivertso** [snyk-tech-services/backstage-plugin-snyk#36]
- `node -v`: v14.17.5
- `npm -v`: 6.14.14
- OS: (e.g. OSX, Linux, Windows, ...) Debian GNU/Linux 10 (buster)

### Expected behaviour
Installing plugin on a backstage application should work.

### Actual behaviour
In the "Security" (Snyk) tab, I'm getting below error:
> No Snyk org/project-ids listed

This is happening probably due to [this](https://github.com/snyk-tech-services/backstage-plugin-snyk/blob/develop/src/components/SnykEntityComponent/SnykOverviewComponent.tsx#L22-L24) code:
```
if (!entity || !entity?.metadata.name) {
  return <>No Snyk org/project-ids listed</>;
}
```
But our projects have `metadata.name`, `metadata.annotations.snyk.io/org-name` and `metadata.annotations.snyk.io/project-ids` defined:
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: foo
  description: foo
  annotations:
    snyk.io/org-name: foo
    snyk.io/project-ids: foo
```

### Steps to reproduce
- Create a backstage application.
- Run `yarn backstage-cli versions:bump` to ensure packages are updated.
- Pin `tech-radar` to `0.4.4` due to [this](https://github.com/Qix-/color/issues/213#issuecomment-897036602) issue.
